spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect:
          storage_engine: innodb
        format_sql: false
        show_sql: false
        use_sql_comments: false
    open-in-view: false


logging:
  level:
    io.github.dongdong8343.skinroutine: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.security: TRACE